spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/bankDB?useSSL=false
  application:
    name: sn-bank
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

server:
  servlet:
    session:
      timeout: 30m

data:
  secret-key: dtj8WL8jwm49LhXyXnscpXTv5uc5VhWm+WWN5pkDejo=