spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/bankDB?useSSL=false&allowPublicKeyRetrieval=true
  application:
    name: sn-bank
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization:  true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    session:
      timeout: 30m

data:
  secret-key: dtj8WL8jwm49LhXyXnscpXTv5uc5VhWm+WWN5pkDejo=

exchange-rate:
  naver:
    host: https://m.search.naver.com
    url: /p/csearch/content/qapirender.nhn
    request-param:
      key: calculator
      pkid: 141
      q: "%ED%99%98%EC%9C%A8"
      where: m
      u1: keb
      u6: standardUnit
      u7: 0
      u3: USD
      u4: KRW
      u8: down
      u2: 1

serverIp: 13.209.87.161