name: Java Build & Coverage  CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**.java'
      - '**.yml'
      - '**.properties'
      - 'build.gradle'
      - 'settings.gradle'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - 2181:2181
        options: >-
          --health-cmd "echo ruok | nc localhost 2181 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      kafka:
        image: confluentinc/cp-kafka
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "kafka-topics --list --bootstrap-server localhost:9092 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: imzero238/Banking-API