name: EC2 Deployment Workflow

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

  #pull_request:
    #types:
      #- closed

jobs:
  deploy:
   # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}